name: Gradle Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Build with Gradle (wrapper)
        run: ./gradlew --no-daemon clean test aggregate -Dheadless=true

      - name: Upload test reports (JUnit)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: build/test-results/test

      - name: Upload Serenity reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: serenity-site
          path: build/reports/serenity